# Generated by Django 3.0.5 on 2020-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Job title', max_length=140),
        ),
    ]
