# Generated by Django 3.0.5 on 2020-05-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200502_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
