# Generated by Django 3.0.5 on 2020-05-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobimage_isthumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobimage',
            old_name='isThumb',
            new_name='isthumb',
        ),
    ]
