# Generated by Django 3.0.5 on 2020-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20200503_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-is_pinned', '-start_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
