# Generated by Django 3.0.7 on 2020-06-10 00:35

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200609_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(default='/default/img.png', upload_to='images/jobs/', validators=[jobs.models.validate_image]),
        ),
    ]
