# Generated by Django 3.0.7 on 2020-07-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20200610_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='description',
            field=models.CharField(default='Image description', max_length=140),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='title',
            field=models.CharField(default='Image title', max_length=80),
        ),
        migrations.CreateModel(
            name='JobEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='Embed iframe')),
                ('title', models.CharField(default='Image title', max_length=80)),
                ('description', models.CharField(default='Image description', max_length=140)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed', to='jobs.Job')),
            ],
        ),
    ]
