# Generated by Django 3.0.7 on 2020-07-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20200704_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobembed',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='jobs.Job'),
        ),
    ]
