# Generated by Django 3.0.7 on 2020-07-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20200705_0045'),
        ('jobs', '0017_auto_20200705_0046'),
    ]

    operations = [
    ]
