# Generated by Django 3.0.7 on 2020-07-09 15:23

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_merge_20200705_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Element title', max_length=80)),
                ('description', models.CharField(blank=True, default='Element description', max_length=140)),
                ('body', models.TextField(default='Embed iframe')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='jobs.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Element title', max_length=80)),
                ('description', models.CharField(blank=True, default='Element description', max_length=140)),
                ('image', models.ImageField(default='/default/img.png', upload_to='images/jobs/', validators=[jobs.models.validate_image])),
                ('is_cover', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='job',
        ),
        migrations.DeleteModel(
            name='JobEmbed',
        ),
        migrations.DeleteModel(
            name='JobImage',
        ),
    ]
