# Generated by Django 3.0.7 on 2020-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20200709_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryembed',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='galleryembed',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
