# Generated by Django 3.0.5 on 2020-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_certification_idiom_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(default='Certification Title', max_length=100),
        ),
    ]
