# Generated by Django 3.0.7 on 2020-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200709_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
