# Generated by Django 3.0.7 on 2020-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200709_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
