# Generated by Django 3.0.7 on 2020-07-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['grade', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('instructions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructions', to='divertida.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='interactive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interactive', to='divertida.Interactive'),
        ),
    ]
