# Generated by Django 3.0.7 on 2020-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='interactive',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
