# Generated by Django 3.0.7 on 2020-07-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0002_auto_20200722_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
