# Generated by Django 3.0.7 on 2020-07-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0003_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='index',
        ),
        migrations.AlterField(
            model_name='card',
            name='grade',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=1),
        ),
    ]
