# Generated by Django 3.0.7 on 2020-07-23 20:24

import divertida.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0004_auto_20200722_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('K', 'Preescolar'), ('P', 'Primaria'), ('S', 'Secundaria')], max_length=1)),
                ('year', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(default='/default/img.png', upload_to='divertida/images/jobs/', validators=[divertida.models.validate_image])),
            ],
            options={
                'ordering': ['grade', 'year'],
            },
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['book', 'index']},
        ),
        migrations.RemoveField(
            model_name='card',
            name='grade',
        ),
        migrations.AlterField(
            model_name='card',
            name='index',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='card',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book', to='divertida.Book'),
        ),
    ]
