# Generated by Django 3.0.7 on 2020-07-23 21:33

import divertida.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0005_auto_20200723_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='image',
            field=models.ImageField(null=True, upload_to='divertida/images/interacts/', validators=[divertida.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='divertida/images/books/', validators=[divertida.models.validate_image]),
        ),
    ]
