# Generated by Django 3.0.7 on 2020-08-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divertida', '0007_auto_20200723_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='book',
        ),
        migrations.RemoveField(
            model_name='card',
            name='interactive',
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='card',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Instructions',
        ),
        migrations.DeleteModel(
            name='Interactive',
        ),
    ]
