# Generated by Django 3.0.7 on 2020-09-24 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('is_pinned', models.BooleanField(default=False)),
                ('privacy', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-date'],
            },
        ),
    ]
